#!/bin/bash
# Install git hooks for this repository

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

# Ensure hooks directory exists
mkdir -p "$HOOKS_DIR"

# Create pre-commit hook that calls export-requirements.sh
cat > "$HOOKS_DIR/pre-commit" <<'HOOK'
#!/bin/bash
# Auto-generated by scripts/install-hooks.sh

# Get the repository root directory
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Run the export-requirements script
"$REPO_ROOT/scripts/export-requirements.sh"
HOOK

# Make the hook executable
chmod +x "$HOOKS_DIR/pre-commit"

echo "✓ Git hooks installed successfully!"
echo "  - pre-commit: Auto-export requirements.txt when uv.lock changes"
echo ""
echo "To skip hooks on commit, use: git commit --no-verify"
